# Compiler and flags
CXX = g++
CXXFLAGS = -std=c++11 -Wall

# Targets for each part
all: part_a part_b part_c

part_a: part_a.cpp
	$(CXX) $(CXXFLAGS) -o part_a part_a.cpp

part_b: part_b.cpp
	$(CXX) $(CXXFLAGS) -o part_b part_b.cpp

part_c: part_c.cpp
	$(CXX) $(CXXFLAGS) -o part_c part_c.cpp

clean:
	rm -f part_a part_b part_c

