# Makefile for Practice Activity 8 - Ali Younes

CXX = g++
CXXFLAGS = -std=c++17 -g -O0
TARGET = pa8
SRC = prices.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)

